### ISSUE TITLE
[HELP]:  Unable to start course

### ISSUE THREAD

**Issue by realtebo** [freeCodeCamp/near-curriculum#23]
### Project

[near-curriculum](https://github.com/freeCodeCamp/near-curriculum)

### Lesson Number

Unable to start course

### Question

After executing the build of container,  I run FreeCodeCamp -> Run Course but I got this after clicking of first link

![image](https://user-images.githubusercontent.com/1268699/203317166-07730d44-daed-4558-8b92-adb801618f76.png)

I am on a Windows 11 
- I tried on a total of 3 pc, all of 3 with windows 11, 2 using Hyper-V and 1 using WSL.
- Same issue.

### Console output
```

root@67916d1f6e6e:/workspace/near-curriculum# cd . && NODE_ENV=production node ./.freeCodeCamp/tooling/server.js
🔵 INFO:  2022-11-22 07:43:54 Listening on port 8080
🔵 INFO:  2022-11-22 07:43:56 Watching for file changes on /workspace/near-curriculum
file:///workspace/near-curriculum/.freeCodeCamp/tooling/parser.js:200
  const mat = lesson.match(
                     ^

TypeError: Cannot read properties of undefined (reading 'match')
    at parseMarker (file:///workspace/near-curriculum/.freeCodeCamp/tooling/parser.js:200:22)
    at getLessonDescription (file:///workspace/near-curriculum/.freeCodeCamp/tooling/parser.js:62:23)
    at runLesson (file:///workspace/near-curriculum/.freeCodeCamp/tooling/lesson.js:35:23)

Node.js v18.12.1
```

I checkout also my git status

```
> git branch
* main
```

```
git log  -n 1
commit f1dd8a4c02f320d4fc0038a2b112dcea3d3fc50e (HEAD -> main, origin/next, origin/main, origin/HEAD)
Merge: 0de9f11 0da0c32
Author: Tom <20648924+moT01@users.noreply.github.com>
Date:   Mon Nov 14 10:28:38 2022 -0600

    Merge pull request #22 from moT01/feat/updated-courses-to-1-7-1

    feat: update courses extension to 1.7.1
```

Should I execute some command on local pc, on local folder, before running?

**Comment by realtebo** [comment]
Theory: I am following the js code. I noticed that this happens because there is no 'lesson' at some point.

I see, in fact, only 2 main links, the first has something link "0/57" on bottom-right. 
Could be the 'zero' and indicator that something is missing? 
Does the course download the index from something online but it's actually not retrieved?

**Comment by realtebo** [comment]
I scratched out all and restarted.

This time the project is updated, so I git pulled. 

I restarted the build of container 
I started the course using freedCodeCamp extension -> run Course

I see this

![image](https://user-images.githubusercontent.com/1268699/204769411-c8279d79-ea89-4fea-82b6-b136b6af38ad.png)

Then I click on first box and again i get

![image](https://user-images.githubusercontent.com/1268699/204769490-ed490708-4ece-4fee-afe6-fc60e1ae1198.png)

Already tried to stop and restart course, no lucky.

About config/projects.json the current lesson was already at 1

  {
    "id": 0,
    "title": "Learn How to Set Up NEAR by Building a Hello World Smart Contract",
    "dashedName": "learn-how-to-set-up-near-by-building-a-hello-world-smart-contract",
    "isIntegrated": false,
    "description": "In this course, you will learn how to set up NEAR by building a simple hello world application.",
    "isPublic": true,
    "currentLesson": 1,
    "runTestsOnWatch": true
  },

**Comment by realtebo** [comment]
Same output error in the extension console

```
Watching for file changes on /workspace/near-curriculum
file:///workspace/near-curriculum/.freeCodeCamp/tooling/parser.js:200
  const mat = lesson.match(
                     ^

TypeError: Cannot read properties of undefined (reading 'match')
    at parseMarker (file:///workspace/near-curriculum/.freeCodeCamp/tooling/parser.js:200:22)
    at getLessonDescription (file:///workspace/near-curriculum/.freeCodeCamp/tooling/parser.js:62:23)
    at runLesson (file:///workspace/near-curriculum/.freeCodeCamp/tooling/lesson.js:35:23)
    at async FSWatcher.<anonymous> (file:///workspace/near-curriculum/.freeCodeCamp/tooling/hot-reload.js:47:7)

Node.js v18.12.1
```

**Comment by realtebo** [comment]
Side note: I've the same identical problem with solana-curriculum.

**Comment by realtebo** [comment]
Idea: should I force english locale some where ? I see that markdown files is under a locale/english folder?

**Comment by moT01** [comment]
I really don't know what to tell you @realtebo. I'm not having any issues. Like I said, I see the error from time to time, but I just fire the course back up and it works. For it to never work for you... not sure. Do you have a mac or linux box to try on? I will give it a try it on my windows machine when I get a chance to see if I can reproduce.

You can run `node tooling/camper-info.js` and share the output. I'm not optimistic it will give us anything more to go on, but it might.

**Comment by realtebo** [comment]
I builded a 4th pc.

This has windows 11, but this time I installed wsl 2 so docker is running into wsl 2 instead of hyper-v

Now I can see the start page into the integrated browser, but ... NO CLICK is working. Clicking, it doesn't do anything.

Also, the link to this very issue tracker is not working.

Note this: when I click, i see this

![image](https://user-images.githubusercontent.com/1268699/214394726-166e121f-4552-4e87-aea7-6b3a9711fd0c.png)

Please note that words, in italian. They means "State block is active" or "block active state" ... italian is a strange language ... when missing connectors and verbs is difficult to translated. 

Any other suggestion?

Oh... a good news is that something is working because when I click on a start page div, I see project code changing. But it's always pointing to an empty file

![image](https://user-images.githubusercontent.com/1268699/214395237-740a70ec-b2f0-4080-a5e3-d0361ac6ec2e.png)

![image](https://user-images.githubusercontent.com/1268699/214395266-ffd8c9e6-4ce7-4d21-a9e5-19e11f0c7810.png)

**Comment by realtebo** [comment]
this could be usefull to you ?

![image](https://user-images.githubusercontent.com/1268699/214396546-54e76698-72e2-43e8-8c51-27fc4ed07b38.png)

**Comment by ShaunSHamilton** [comment]
@realtebo Thank you for the extra information to work with.

> Please note that words, in italian. They means "State block is active" or "block active state"

You can ignore that message - it is just VSCode's Simple Browser telling you the webview is in focus (you clicked on it, and your keyboard events are now targeting the preview).

---

> It seems ok inside ...

Those screenshots are useful, but you are correct - it does seem ok inside.

---

Can you try running `freeCodeCamp: Develop Course` instead of `freeCodeCamp: Run Course`? If you encounter the same issue, there should be more output in the `freeCodeCamp` terminal which you can share here for further debugging.
